// Defining chatrooms action types

const ChatRoomActionTypes = {
  FETCH_CHATROOMS_START: "FETCH_CHATROOMS_START",
  FETCH_CHATROOMS_SUCCESS: "FETCH_CHATROOMS_SUCCESS",
  FETCH_CHATROOMS_FAILURE: "FETCH_CHATROOMS_FAILURE",
  ADD_CHATROOM: "ADD_CHATROOM",
  REMOVE_CHATROOM: "REMOVE_CHATROOM",
  CHATROOM_MODIFICATION_SUCCESS: "CHATROOM_MODIFICATION_SUCCESS",
  CHATROOM_MODIFICATION_FAILURE: "CHATROOM_MODIFICATION_FAILURE",
};

export default ChatRoomActionTypes;
